/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan3;

import javax.swing.JOptionPane;

/**
 *
 * @author VanThuan
 */
public class CongTruNhanChia extends javax.swing.JFrame {

    /**
     * Creates new form DemoCongTruNhanChia
     */
    public CongTruNhanChia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        UpPanel = new javax.swing.JPanel();
        Congtrunhanchia = new javax.swing.JLabel();
        DownPanel = new javax.swing.JPanel();
        Xanh = new javax.swing.JPanel();
        Đỏ = new javax.swing.JPanel();
        Vàng = new javax.swing.JPanel();
        pnTacVu = new javax.swing.JPanel();
        btnGiai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        PannelNhap = new javax.swing.JPanel();
        lbla = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        txtb = new javax.swing.JTextField();
        pnChonPhepTinh = new javax.swing.JPanel();
        radCong = new javax.swing.JRadioButton();
        radTru = new javax.swing.JRadioButton();
        radNhan = new javax.swing.JRadioButton();
        radChia = new javax.swing.JRadioButton();
        lblKetQua = new javax.swing.JLabel();
        txtkq = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cộng - Trừ - Nhân - Chia");
        setResizable(false);

        pnMain.setLayout(new java.awt.BorderLayout());

        Congtrunhanchia.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Congtrunhanchia.setForeground(new java.awt.Color(0, 0, 255));
        Congtrunhanchia.setText("Cộng Trừ Nhân Chia");
        UpPanel.add(Congtrunhanchia);

        pnMain.add(UpPanel, java.awt.BorderLayout.PAGE_START);

        DownPanel.setBackground(new java.awt.Color(255, 153, 153));

        Xanh.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout XanhLayout = new javax.swing.GroupLayout(Xanh);
        Xanh.setLayout(XanhLayout);
        XanhLayout.setHorizontalGroup(
            XanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        XanhLayout.setVerticalGroup(
            XanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        Đỏ.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout ĐỏLayout = new javax.swing.GroupLayout(Đỏ);
        Đỏ.setLayout(ĐỏLayout);
        ĐỏLayout.setHorizontalGroup(
            ĐỏLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ĐỏLayout.setVerticalGroup(
            ĐỏLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        Vàng.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout VàngLayout = new javax.swing.GroupLayout(Vàng);
        Vàng.setLayout(VàngLayout);
        VàngLayout.setHorizontalGroup(
            VàngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        VàngLayout.setVerticalGroup(
            VàngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DownPanelLayout = new javax.swing.GroupLayout(DownPanel);
        DownPanel.setLayout(DownPanelLayout);
        DownPanelLayout.setHorizontalGroup(
            DownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DownPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(Xanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Đỏ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Vàng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        DownPanelLayout.setVerticalGroup(
            DownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DownPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(DownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Xanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vàng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Đỏ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pnMain.add(DownPanel, java.awt.BorderLayout.PAGE_END);

        pnTacVu.setBackground(new java.awt.Color(204, 204, 204));
        pnTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Chọn tác vụ:"));

        btnGiai.setText("Giải");
        btnGiai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTacVuLayout = new javax.swing.GroupLayout(pnTacVu);
        pnTacVu.setLayout(pnTacVuLayout);
        pnTacVuLayout.setHorizontalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTacVuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnGiai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnTacVuLayout.setVerticalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGiai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoat)
                .addGap(0, 0, 0))
        );

        pnMain.add(pnTacVu, java.awt.BorderLayout.LINE_START);

        PannelNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Nhập 2 số a & b:"));

        lbla.setText("Nhập a:");

        lblb.setText("Nhập b:");

        pnChonPhepTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chọn phép tính:"));
        pnChonPhepTinh.setLayout(new java.awt.GridLayout(2, 2));

        buttonGroup1.add(radCong);
        radCong.setSelected(true);
        radCong.setText("Cộng");
        pnChonPhepTinh.add(radCong);

        buttonGroup1.add(radTru);
        radTru.setText("Trừ");
        pnChonPhepTinh.add(radTru);

        buttonGroup1.add(radNhan);
        radNhan.setText("Nhân");
        pnChonPhepTinh.add(radNhan);

        buttonGroup1.add(radChia);
        radChia.setText("Chia");
        pnChonPhepTinh.add(radChia);

        lblKetQua.setText("Kết quả:");

        txtkq.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout PannelNhapLayout = new javax.swing.GroupLayout(PannelNhap);
        PannelNhap.setLayout(PannelNhapLayout);
        PannelNhapLayout.setHorizontalGroup(
            PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelNhapLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKetQua)
                    .addComponent(lblb)
                    .addComponent(lbla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtkq, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PannelNhapLayout.createSequentialGroup()
                        .addComponent(pnChonPhepTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PannelNhapLayout.setVerticalGroup(
            PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla)
                    .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnChonPhepTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PannelNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKetQua))
                .addGap(10, 10, 10))
        );

        pnMain.add(PannelNhap, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int ret = JOptionPane.showConfirmDialog(null, "Thoát chương trình!", "Thoát", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiActionPerformed
        String text = txta.getText().trim();
        double a = 0, b = 0;
        try {
            a = Double.parseDouble(text);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nhập sai định dạng!");
            txta.selectAll();
            txta.requestFocus();
            return;
        }
        text = txtb.getText().trim();
        try {
            b = Double.parseDouble(text);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nhập sai định dạng!");
            txtb.selectAll();
            txtb.requestFocus();
            return;
        }

        double kq = 0;
        if (radCong.isSelected()) {
            kq = (a + b);
        } else if (radTru.isSelected()) {
            kq = (a - b);
        } else if (radNhan.isSelected()) {
            kq = (a * b);
        } else if (radChia.isSelected()) {
            if (b != 0) {
                kq = (a * 1.0 / b * 1.0);
            } else {
                JOptionPane.showMessageDialog(null, "b phải khác 0 !");
                txtb.selectAll();
                txtb.requestFocus();
            }
        }
        txtkq.setText(kq + "");
    }//GEN-LAST:event_btnGiaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        txta.setText("");
        txtb.setText("");
        txtkq.setText("");
        txta.requestFocus();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongTruNhanChia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongTruNhanChia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongTruNhanChia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongTruNhanChia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CongTruNhanChia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Congtrunhanchia;
    private javax.swing.JPanel DownPanel;
    private javax.swing.JPanel PannelNhap;
    private javax.swing.JPanel UpPanel;
    private javax.swing.JPanel Vàng;
    private javax.swing.JPanel Xanh;
    private javax.swing.JButton btnGiai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lblb;
    private javax.swing.JPanel pnChonPhepTinh;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTacVu;
    private javax.swing.JRadioButton radChia;
    private javax.swing.JRadioButton radCong;
    private javax.swing.JRadioButton radNhan;
    private javax.swing.JRadioButton radTru;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtkq;
    private javax.swing.JPanel Đỏ;
    // End of variables declaration//GEN-END:variables
}
