package Tuan3;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VanThuan
 */
public class DemoCaculator extends javax.swing.JFrame {

    /**
     * Creates new form DemoCaculator
     */
    public DemoCaculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hienthi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnchia = new javax.swing.JButton();
        sqrtcan2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnnhan = new javax.swing.JButton();
        btnphantram = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btntru = new javax.swing.JButton();
        btn1phanx = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnam = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btncong = new javax.swing.JButton();
        btnbang = new javax.swing.JButton();

        jButton10.setText("jButton10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        hienthi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        hienthi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienthi.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(hienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btnchia.setText("/");
        btnchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnchia);

        sqrtcan2.setText("sqrt");
        sqrtcan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtcan2ActionPerformed(evt);
            }
        });
        jPanel2.add(sqrtcan2);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btnnhan.setText("*");
        btnnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnnhan);

        btnphantram.setText("%");
        btnphantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphantramActionPerformed(evt);
            }
        });
        jPanel2.add(btnphantram);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btntru.setText("-");
        btntru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruActionPerformed(evt);
            }
        });
        jPanel2.add(btntru);

        btn1phanx.setText("1/x");
        btn1phanx.setToolTipText("");
        btn1phanx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1phanxActionPerformed(evt);
            }
        });
        jPanel2.add(btn1phanx);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btnam.setText("+/-");
        btnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamActionPerformed(evt);
            }
        });
        jPanel2.add(btnam);

        btnreset.setText("C");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel2.add(btnreset);

        btncong.setText("+");
        btncong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncongActionPerformed(evt);
            }
        });
        jPanel2.add(btncong);

        btnbang.setText("=");
        btnbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbangActionPerformed(evt);
            }
        });
        jPanel2.add(btnbang);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnamActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn1.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn2.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn3.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn4.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn5.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn6.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn8.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn9.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn0.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn0ActionPerformed
    private long a=0;
    private String phepToan="";
    private void btnchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaActionPerformed
        // TODO add your handling code here:
          this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="/";
              this.hienthi.setText("0");
          }
        
    }//GEN-LAST:event_btnchiaActionPerformed

    private void btnnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanActionPerformed
        // TODO add your handling code here:
         this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="*";
              this.hienthi.setText("0");
          }
    }//GEN-LAST:event_btnnhanActionPerformed

    private void btntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruActionPerformed
        // TODO add your handling code here:
         this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="-";
              this.hienthi.setText("0");
          }
        
    }//GEN-LAST:event_btntruActionPerformed

    private void btncongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncongActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="+";
              this.hienthi.setText("0");
          } 
        
    }//GEN-LAST:event_btncongActionPerformed

    private void sqrtcan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtcan2ActionPerformed
        // TODO add your handling code here:
         this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="sqrt";
              this.hienthi.setText("0");
          }
    }//GEN-LAST:event_sqrtcan2ActionPerformed

    private void btnphantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphantramActionPerformed
        // TODO add your handling code here:
         this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="%";
              this.hienthi.setText("0");
          }
    }//GEN-LAST:event_btnphantramActionPerformed

    private void btn1phanxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1phanxActionPerformed
        // TODO add your handling code here:
         this.a = Long.parseLong(hienthi.getText());
          if(this.a!=0){
              this.phepToan ="1/a";
              this.hienthi.setText("0");
          }
    }//GEN-LAST:event_btn1phanxActionPerformed

    private void btnbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbangActionPerformed
        // TODO add your handling code here:
        if(this.phepToan.length()>0){
            long b = Long.parseLong(this.hienthi.getText());
            if(this.phepToan.equals("+")){
                long kq = this.a +b;
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("-")){
                long kq = this.a -b;
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("*")){
                long kq = this.a*b;
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("/")){
                float kq = this.a/b;
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("sqrt")){
                double kq = Math.sqrt(this.a);
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("%")){
                double kq = this.a%100;
                this.hienthi.setText(String.valueOf(kq));
            }else if(this.phepToan.equals("1/a")){
                long kq = 1/(this.a);
                long kq1 = 1%(this.a);
                this.hienthi.setText(String.valueOf(kq+"."+kq1));
            }
        }
    }//GEN-LAST:event_btnbangActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        this.phepToan="";
        this.a=0;
        this.hienthi.setText("0");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
          String gt= this.hienthi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+btn7.getText());
            this.hienthi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoCaculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoCaculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoCaculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoCaculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoCaculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1phanx;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnam;
    private javax.swing.JButton btnbang;
    private javax.swing.JButton btnchia;
    private javax.swing.JButton btncong;
    private javax.swing.JButton btnnhan;
    private javax.swing.JButton btnphantram;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntru;
    private javax.swing.JLabel hienthi;
    private javax.swing.JButton jButton10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton sqrtcan2;
    // End of variables declaration//GEN-END:variables
}
